[package]
name = "releasecraftsman"
version = "0.1.1"
edition = "2021"

[dependencies]
colored = "2.0.4"
clap = "2.33.3"
chat-gpt-lib-rs = "0.2.1"
tokio = { version = "1.32.0", features = ["full"] }
include_dir = "0.7.3"
spinoff = "0.8.0"
inquire = "0.6.2"
log = "0.4.20"
